spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bazzaar_db}
    username: ${SPRING_DATASOURCE_USERNAME:bazzaardb}
    password: ${SPRING_DATASOURCE_PASSWORD:bazzaarDbPass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mdsoufiane.dev@gmail.com
    password: xmke dvyh brxm kgze
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  cloud:
    config:
      override.system-properties: false
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP:false}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

application:
  media:
    upload-root-path: ${APP_MEDIA_UPLOAD_ROOT_PATH:/app/uploads}
    allowed-content-types:
      - image/jpeg
      - image/png
      - image/webp
      - image/gif
    max-file-size-bytes: 5242880         # 5 MB

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always