server:
  port: 8088

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP:false}